CREATE SEQUENCE seq_cargo
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_empleado
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_venta
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_cliente
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_pedido
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_pago
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_factura
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_detalle_pedido
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_compra_proveedor
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_proveedor
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_inventarios
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE seq_detalle_producto
START WITH 1
INCREMENT BY 1;
