DROP TABLE ciudad;
DROP TABLE hotel;
DROP TABLE SOLICITUD_RESERVA;
DROP TABLE estado;
DROP TABLE aerolinea;
DROP TABLE pago;
DROP TABLE VUELO;
DROP TABLE RESERVA_AVION;
DROP TABLE RESERVA_HOTEL;
DROP TABLE reserva;
DROP TABLE cliente;
DROP TABLE VIAJERO;
DROP TABLE fecha_reserva;

