CREATE INDEX idx_nombre_ciudad ON ciudad(nombre_ciudad);
CREATE INDEX idx_nombre_hotel ON hotel(nombre_hotel);
CREATE INDEX idx_fecha_aprobacion ON estado(fecha_aprobacion);
CREATE INDEX idx_nombre_aerolinea ON aerolinea(nombre_aerolinea);
CREATE INDEX idx_fecha_pago ON pago(fecha_pago);
CREATE INDEX idx_numero_vuelo ON vuelo(numero_vuelo);
CREATE INDEX idx_clase ON reserva_avion(clase);
CREATE INDEX idx_tipo_acomodacion ON reserva_hotel(tipo_acomodacion);
CREATE INDEX idx_nombre_cliente ON cliente(nombre_cliente, apellido_cliente);
CREATE INDEX idx_nombre_viajero ON viajero(nombre_viajero);
